name = "smart-restaurant"
main = "dist/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "db-smart-restaurant"
database_id = "placeholder"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "assets-smart-restaurant"
